version: "3"

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    command: sleep infinity
    logging:
      driver: local
    env_file:
      - .env
    volumes:
      - ".:/home/vscode/workspace:z"
      - ".gradle-cache:/home/vscode/.gradle:z"
      - ".vscode-server:/home/vscode/.vscode-server:z"
