micronaut:
  application:
    name: edumgmt
  server:
    context-path: /${micronaut.application.name}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    intercept-url-map:
      - pattern: /exception/**
        access: isAnonymous()
      - pattern: /swagger/**
        access: isAuthenticated()
      - pattern: /swagger-ui/**
        access: isAuthenticated()
      - pattern: /student/**
        access: isAnonymous()
      - pattern: /attendance/**
        access: isAnonymous()

datasources:
  default:
    url: jdbc:h2:./.h2/edumgmt;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: false
        format_sql: false

liquibase:
  datasources:
    default:
      change-log: classpath:/db/db.changelog-main.yml

logger:
  levels:
    com.anasdidi.edumgmt: DEBUG

edumgmt:
  basic-auth:
    username: anas
    password: password
