micronaut:
  application:
    name: edumgmt
  server:
    context-path: /${micronaut.application.name}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:h2:tcp://db:1521/${micronaut.application.name}
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    dialect: H2
    create-schema: CREATE_DROP

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
