micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
        generator:
          refresh-token:
            secret: pleaseChangeThisSecretForANewOne
        claims-validators:
          issuer: jwt-issuer

datasources:
  default:
    url: jdbc:h2:./.h2/edumgmt;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090
    username: sa
    password: sa

jpa:
  default:
    properties:
      hibernate:
        show_sql: true

logger:
  levels:
    com.anasdidi.edumgmt: TRACE

edumgmt:
  basic-auth:
    username: anas
    password: password
  super-admin:
    password: ${random.shortuuid}
