--liquibase formatted sql

--changeset anas:0.1.0-1
CREATE TABLE PUBLIC.T_STUDENT (
	ID UUID NOT NULL,
	NM CHARACTER VARYING NOT NULL,
	CONSTRAINT PK_STUDENT PRIMARY KEY (ID)
);
--rollbank DROP TABLE T_STUDENT;
