--liquibase formatted sql

--changeset anas:1.t_student-1-1
CREATE TABLE PUBLIC.T_STUDENT (
	ID UUID NOT NULL,
	NM CHARACTER VARYING NOT NULL,
  IS_DEL BOOLEAN DEFAULT FALSE DEFAULT ON NULL NOT NULL,
  VER INTEGER NOT NULL,
  CREATE_BY CHARACTER VARYING NOT NULL,
  CREATE_DT TIMESTAMP WITH TIME ZONE NOT NULL,
  UPDATE_BY CHARACTER VARYING NOT NULL,
  UPDATE_DT TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT PK_STUDENT PRIMARY KEY (ID)
);
--rollbank DROP TABLE T_STUDENT;
