--liquibase formatted sql

--changeset anas:3.t_attendance_student-1-1
CREATE TABLE PUBLIC.T_ATTENDANCE_STUDENT (
	ID UUID NOT NULL,
  ATTENDANCE_ID UUID NOT NULL,
  STUDENT_ID UUID NOT NULL,
  IS_DEL BOOLEAN DEFAULT FALSE DEFAULT ON NULL NOT NULL,
  VER INTEGER NOT NULL,
  CREATE_BY VARCHAR(20) NOT NULL,
  CREATE_DT TIMESTAMP WITH TIME ZONE NOT NULL,
  UPDATE_BY VARCHAR(20) NOT NULL,
  UPDATE_DT TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT PK_ATTENDANCE_STUDENT PRIMARY KEY(ID),
  CONSTRAINT UQ_ATTENDANCE_STUDENT_ATT_STU_DEL UNIQUE(ATTENDANCE_ID, STUDENT_ID, IS_DEL),
  CONSTRAINT FK_ATT_STU_ATT FOREIGN KEY(ATTENDANCE_ID) REFERENCES PUBLIC.T_ATTENDANCE(ID),
  CONSTRAINT FK_ATT_STU_STU FOREIGN KEY(STUDENT_ID) REFERENCES PUBLIC.T_STUDENT(ID)
);
--rollbank DROP TABLE PUBLIC.T_ATTENDANCE_STUDENT;

--changeset anas:3.t_attendance_student-1-2
CREATE INDEX IX_ATTENDANCE_STUDENT_ATT ON PUBLIC.T_ATTENDANCE_STUDENT(ATTENDANCE_ID);
CREATE INDEX IX_ATTENDANCE_STUDENT_STU ON PUBLIC.T_ATTENDANCE_STUDENT(STUDENT_ID);
--rollback DROP INDEX IX_ATTENDANCE_STUDENT_ATT, IX_ATTENDANCE_STUDENT_STU;
