--liquibase formatted sql

--changeset anas:4.t_user-1-1
CREATE TABLE PUBLIC.T_USER (
	ID UUID NOT NULL,
  USER_ID VARCHAR(20) NOT NULL,
  PWD VARCHAR(100) NOT NULL,
  NM VARCHAR(200) NOT NULL,
  IS_DEL BOOLEAN DEFAULT FALSE DEFAULT ON NULL NOT NULL,
  VER INTEGER NOT NULL,
  CREATE_BY VARCHAR(20) NOT NULL,
  CREATE_DT TIMESTAMP WITH TIME ZONE NOT NULL,
  UPDATE_BY VARCHAR(20) NOT NULL,
  UPDATE_DT TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT PK_USER PRIMARY KEY(ID),
  CONSTRAINT UQ_USER_ID_DEL UNIQUE(USER_ID, IS_DEL)
);
--rollbank DROP TABLE PUBLIC.T_USER;

--changeset anas:4.t_user-1-2
CREATE INDEX IX_USER_USER_ID ON PUBLIC.T_USER(USER_ID);
--rollback DROP INDEX IX_USER_USER_ID;
