--liquibase formatted sql

--changeset anas:5.t_user_token-1-1
CREATE TABLE PUBLIC.T_USER_TOKEN (
	ID UUID NOT NULL,
  USER_ID VARCHAR(20) NOT NULL,
  TOKEN VARCHAR(100) NOT NULL,
  IS_DEL BOOLEAN DEFAULT FALSE DEFAULT ON NULL NOT NULL,
  VER INTEGER NOT NULL,
  CREATE_BY VARCHAR(20) NOT NULL,
  CREATE_DT TIMESTAMP WITH TIME ZONE NOT NULL,
  UPDATE_BY VARCHAR(20) NOT NULL,
  UPDATE_DT TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT PK_USER_TOKEN PRIMARY KEY(ID)
);
--rollbank DROP TABLE PUBLIC.T_USER_TOKEN;

--changeset anas:5.t_user_token-1-2
CREATE INDEX IX_USER_TOKEN_TOKEN ON PUBLIC.T_USER_TOKEN(TOKEN);
--rollback DROP INDEX IX_USER_TOKEN_TOKEN;
