--liquibase formatted sql

--changeset anas:1.t_student-1-1
CREATE TABLE PUBLIC.T_STUDENT (
	ID UUID NOT NULL,
	NM CHARACTER VARYING NOT NULL,
  VER INTEGER NOT NULL,
	CONSTRAINT PK_STUDENT PRIMARY KEY (ID)
);
--rollbank DROP TABLE T_STUDENT;
